### ISSUE TITLE
Unable to run the Frontend

### ISSUE THREAD

**Issue by rvk7895** [nammayatri/nammayatri#8328]
**Describe the bug**
Unable to run the Frontend Successfully following the instruction. After running `npm start` the only thing visible on the link is **App is Ready**. 

The console log also shows the following:
```
Uncaught ReferenceError: JBridge is not defined
    at eval (parseParams.js:36:149)
    at ./node_modules/presto-ui/src/helpers/android/parseParams.js (index_bundle.js:4485:1)
    at __webpack_require__ (index_bundle.js:20:30)
    at eval (index.js:35:20)
    at ./node_modules/presto-ui/src/helpers/android/index.js (index_bundle.js:4449:1)
    at __webpack_require__ (index_bundle.js:20:30)
    at eval (android.js:93:19)
    at ./node_modules/presto-ui/src/doms/android.js (index_bundle.js:4401:1)
    at __webpack_require__ (index_bundle.js:20:30)
    at run (index.js:28:12)
```

**To Reproduce**
Steps mentioned in the `Frontend Directory` to run an iOS app.

**Screenshots**
![image](https://github.com/user-attachments/assets/35054423-2706-4c8a-8363-fd1407efef82)

**App (please complete the following information):**
- Ubuntu 24.04

**Comment by Ajaymalviy** [comment]
same issue with me??
